name: py312
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - jupyterlab
  - ipython
  - icecream
  - pillow
  - statsmodels
  - xgboost
  - lightgbm
  - plotly
  - bokeh
  - altair
  #- opencv-python
  - dask
  - pyarrow
  - fastparquet
  - nltk
  - spacy
  - ipywidgets
  - numba
  - cython
  - loguru

