name: HF
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - nodejs
  - numpy
  - pandas
  - transformers
  - pytorch
  - torchvision
  - accelerate
  - datasets
  - evaluate
  - scikit-learn
  - matplotlib
  - jupyterlab
  - ipywidgets
  - ipython
  - openjdk
  - pip:
    - gradio
    - huggingface_hub
    - optimum
    - diffusers
    - langchain
    - chromadb
